#Definir los servicios que va a tener nuestro docker
version: "2.4"


services:
  postgres:
    image: postgres
    mem_limit: 1024m
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - /Users/micae/OneDrive/Escritorio/Arquitectura_de_Software/Docker/var/lib/postgresql/data
    networks:
      - micaela-network
  currency-converter:
    image: demo:3.0.0
    restart: always
    ports:
      - "8008:8008"
    environment:
      DB_URL: ${POSTGRES_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      API_KEY: ${API_KEY}
      API_URL: ${API_URL}
    depends_on:
      - postgres
    networks:
      - micaela-network
  angular:
    image: angular-software:4.0.0
    ports:
      - "4200:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - micaela-network
networks:
    micaela-network:
        driver: bridge
        ipam:
          driver: default
          config:
              - subnet: 172.9.0.0/16
                gateway: 172.9.0.1
    ports: