##Using the external service - correct way
GET http://localhost:8008/api/currency/exchange?to=eur&from=usd&amount=1000

###
##Using the external service - wrong way
GET http://localhost:8008/api/currency/exchange?to=bob&from=usd&amount=0
###
GET http://localhost:8008/api/currency/exchange?to=bob&from=usd&amount=-12