### Usando el servicio externo - forma correcta
GET http://localhost:8008/api/currency/exchange?to=BOB&from=USD&amount=800

### Usando el servicio externo - forma incorrecta: monto cero
GET http://localhost:8008/api/currency/exchange?to=bob&from=usd&amount=0

### Usando el servicio externo - forma incorrecta: monto negativo
GET http://localhost:8008/api/currency/exchange?to=bob&from=usd&amount=-12

### Mostrar la lista de consultas realizadas de cambio de moneda
GET http://localhost:8008/api/currency/list

### Mostrar la lista de consultas realizadas de cambio de moneda en base al CURRENCY_FROM = BOB
GET http://localhost:8008/api/currency/list/from/BOB

### Mostrar la lista de consultas realizadas de cambio de moneda en base al CURRENCY_TO = USD
GET http://localhost:8008/api/currency/list/to/USD

### Mostrar la lista de consultas realizadas de cambio de moneda ordenado de forma ascendente por el monto
GET http://localhost:8008/api/currency/list/asc

### Mostrar la lista de consultas realizadas de cambio de moneda ordenado de forma descendente por el monto
GET http://localhost:8008/api/currency/list/desc

### Mostrar la lista de las 10 primeras consultas realizadas de cambio de moneda
GET http://localhost:8008/api/currency/list/range/1/10